inherit_gem:
  google-style: google-style.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - "test-data-generator/resource/**/*"
    - "gas/workspace/**/*"
    - "gas/artifacts/**/*"

Metrics/BlockLength:
  Exclude:
    - "owlbot-postprocessor/test/test_*.rb"
Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 300
Metrics/PerceivedComplexity:
  Max: 15
Naming/FileName:
  Exclude:
    - "toys/release/*.rb"
Style/Documentation:
  Enabled: false
Style/MixinGrouping:
  Exclude:
    - "owlbot-postprocessor/.toys.rb"
