steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        docker build \
          -t gcr.io/cloud-devrel-public-resources/owlbot-ruby:${TAG_NAME:21} \
          -t gcr.io/cloud-devrel-public-resources/owlbot-ruby:latest \
          -f owlbot-postprocessor/Dockerfile \
          owlbot-postprocessor
images:
  - 'gcr.io/cloud-devrel-public-resources/owlbot-ruby:${TAG_NAME:21}'
  - 'gcr.io/cloud-devrel-public-resources/owlbot-ruby:latest'
