name: CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  CI:
    if: ${{ github.repository == 'googleapis/ruby-common-tools' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "3.2"
            build: true
            jobs: "--only --test"
          - os: ubuntu-latest
            ruby: "3.3"
            build: true
            jobs: "--only --test"
          - os: ubuntu-latest
            ruby: "3.4"
            build: true
            jobs: "--only --test"
          - os: ubuntu-latest
            ruby: "3.4"
            build: false
            jobs: "--only --rubocop"
          - os: ubuntu-latest
            ruby: "4.0"
            build: true
            jobs: "--only --test"
          - os: ubuntu-latest
            ruby: "4.0"
            build: false
            jobs: "--only --rubocop"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install NodeJS 24.x
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: "24.x"
    - name: Install tools and deps
      shell: bash
      run: "gem install --no-document toys && bundle install"
    - name: Test
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      run: toys ci ${{ matrix.jobs }} --include-owlbot-build --github-event-name="$GITHUB_EVENT_NAME" --github-event-payload="${GITHUB_EVENT_PATH}" < /dev/null
